language: python

python:
  - "2.7"
  - "3.6"

notifications:
  email: false

install:
  - pip install cython networkx
  - wget http://scip.zib.de/download/release/scipoptsuite-4.0.0.tgz
  - tar xzf scipoptsuite-4.0.0.tgz
  - cd scipoptsuite-4.0.0/
  - make COMP=clang SHARED=true GMP=false READLINE=false ZIMPL=false
  - make install INSTALLDIR=~/scipoptsuite-4.0.0 COMP=clang SHARED=true GMP=false READLINE=false ZIMPL=false
  - make scipoptlib COMP=clang SHARED=true GMP=false READLINE=false ZIMPL=false
  - cd ..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/scipoptsuite-4.0.0
  - env SCIPOPTDIR=~/scipoptsuite-4.0.0 python setup.py install

script: py.test tests
