language: python

python:
  - "2.7"
  - "3.6"

notifications:
  email: false

install:
  - pip install cython networkx
  - mkdir lib
  - cd lib
  - wget http://scip.zib.de/download.php?fname=libscipopt-4.0.0.linux.x86_64.gnu.opt.so.zip
  - unzip libscipopt-4.0.0.linux.x86_64.gnu.opt.so.zip
  - ln -s libscipopt-4.0.0.linux.x86_64.gnu.opt.so libscipopt.so
  - cd -
  - wget http://scip.zib.de/download/release/scipoptheaders-4.0.0.tgz
  - tar xf scipoptheaders-4.0.0.tgz
  - python setup.py install
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib

script: py.test tests
