language: python

python:
  - "2.7"
  - "3.4"

notifications:
  email: false

install:
  - pip install cython
  - wget http://www.zib.de/miltenberger/test/scipoptsuite-4.0.0.tgz
  - tar xzf scipoptsuite-4.0.0.tgz
  - cd scipoptsuite-4.0.0/
  - make COMP=clang SHARED=true GMP=false READLINE=false ZIMPL=false scipoptlib
  - export SCIPOPTDIR=`pwd`
  - cd ..
  - python setup.py install

script: py.test tests
