language: python

python:
  - "2.7"
  - "3.6"

notifications:
  email: false

install:
  - export VERSION=4.0.0
  - pip install cython networkx
  - wget http://scip.zib.de/download/release/scipoptsuite-$VERSION.tgz
  - tar xzf scipoptsuite-$VERSION.tgz
  - cd scipoptsuite-$VERSION
  - make COMP=clang SHARED=true GMP=false READLINE=false ZIMPL=false
  - make install INSTALLDIR=.. COMP=clang SHARED=true GMP=false READLINE=false ZIMPL=false
  - cd ..
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`pwd`/lib
  - python setup.py install

script: py.test tests
