language: python

python:
  - "2.7"
  - "3.6"

notifications:
  email: false

install:
  - pip install cython networkx
  - wget http://scip.zib.de/download/release/scipoptsuite-4.0.0.tgz
  - tar xzf scipoptsuite-4.0.0.tgz
  - cd scipoptsuite-4.0.0/
  - make COMP=clang SHARED=true GMP=false READLINE=false ZIMPL=false install
  - python setup.py install

script: py.test tests
