language: python

python:
  - "2.7"
  - "3.4"

notifications:
  email: false

install:
  - pip install cython
  - wget http://scip.zib.de/download/release/scipoptsuite-3.2.1.tgz
  - tar xzf scipoptsuite-3.2.1.tgz
  - cd scipoptsuite-3.2.1/
  - rm Makefile.doit
  - wget http://scip.zib.de/download/bugfixes/scip-3.2.1/Makefile.doit
  - make COMP=clang SHARED=true GMP=false READLINE=false ZIMPL=false scipoptlib
  - export SCIPOPTDIR=`pwd`
  - cd ..
  - python setup.py install

script: py.test
