version: 1.1.2 - {build}

image: Visual Studio 2017

branches:
  only:
  - appveyor

environment:
  PYTHON: C:\Python36-x64
  PIP: C:\Python36-x64\Scripts\pip

build_script:
  - cmd: "set PATH=%PYTHON%;%PATH%"
  
  - cmd: "%PIP% install cython networkx pytest"

  - mkdir scipoptdir
    
  - cd scipoptdir
    
  - ps: wget http://scip.zib.de/download/release/scip-4.0.0.win.x86_64.vc14.opt.spx2.lib.zip -outfile scipopt.zip
    
  - ps: wget http://scip.zib.de/download/release/scipoptheaders-4.0.0.zip -outfile headers.zip
    
  - ps: Expand-Archive .\scipopt.zip -DestinationPath lib
    
  - ps: Expand-Archive .\headers.zip -DestinationPath .
    
  - set SCIPOPTDIR = %cd%
    
  - cd ..
    
  - python setup.py install
    
  - set PATH=%SCIPOPTDIR%\lib;%PATH%"

test_script:
- ps: py.test tests
