version: 1.1.2 - {build}

image: Visual Studio 2017

branches:
  only:
  - appveyor

environment:
  PYTHON: C:\Python36-x64

build_script:
- ps: >-
    $env:PYTHON\pip install cython networkx pytest
    
    mkdir scipoptdir
    
    cd scipoptdir
    
    wget http://scip.zib.de/download/release/scip-4.0.0.win.x86_64.vc14.opt.spx2.lib.zip -outfile scipopt.zip
    
    wget http://scip.zib.de/download/release/scipoptheaders-4.0.0.zip -outfile headers.zip
    
    Expand-Archive .\scipopt.zip -DestinationPath lib
    
    Expand-Archive .\headers.zip -DestinationPath .
    
    $env:SCIPOPTDIR = pwd
    
    cd ..
    
    $env:PYTHON\python setup.py install
    
    $env:PATH += ";$env:SCIPOPTDIR\lib"

test_script:
- ps: $env:PYTHON\py.test tests
