version: 1.1.2{build}

branches:
  only:
  - appveyor

build_script:
- ps: >-
    pip install cython networkx
    
    mkdir scipoptdir
    
    cd scipoptdir
    
    wget http://scip.zib.de/download/release/scip-4.0.0.win.x86_64.vc14.opt.spx2.lib.zip -outfile scipopt.zip
    
    wget http://scip.zib.de/download/release/scipoptheaders-4.0.0.zip -outfile headers.zip
    
    Expand-Archive .\scipopt.zip -DestinationPath lib
    
    Expand-Archive .\headers.zip -DestinationPath include
    
    $env:SCIPOPTDIR = pwd
    
    cd ..
    
    python setup.py install
    
    $env:PATH += ";$env:SCIPOPTDIR\lib"

test_script:
- ps: py.test tests
