version: '{build}'

image: Visual Studio 2017

branches:
  only:
  - master

environment:
  PYTHON: C:\Python36-x64
  PIP: C:\Python36-x64\Scripts\pip
  PYTEST: C:\Python36-x64\Scripts\pytest
  TWINE: C:\Python36-x64\Scripts\twine
  SCIPOPTDIR: C:\scipoptdir
  password:
    secure: HEa8MAJyyfSv33snyK3Gleflk9SIfZBxbnTiS39hlWM=

install:
  - cmd: "set PATH=%PYTHON%;%PATH%"
  - cmd: "%PIP% install cython networkx pytest wheel twine"
  - ps: wget http://scip.zib.de/download/release/SCIPOptSuite-4.0.1-win64.exe -outfile scipopt-installer.exe
  - scipopt-installer.exe /S /D=%SCIPOPTDIR%
  - set PATH=%SCIPOPTDIR%\lib;%PATH%"

build_script:
  - python setup.py install

test_script:
  - cmd: "%PYTEST% tests"

artifacts:
  - path: dist\*

after_test:
  - cmd: "echo [pypi] > %USERPROFILE%\\.pypirc"
  - cmd: "echo username: pyscipopt >> %USERPROFILE%\\.pypirc"
  - cmd: "echo password: %password% >> %USERPROFILE%\\.pypirc"
  - python setup.py bdist_wheel
  - cmd: "if [%APPVEYOR_REPO_TAG%]==[true] %TWINE% upload dist\\*.whl"
